/*
Copyright 2005, The Regents of the University
of California. This software was produced under
a U.S. Government contract (W-7405-ENG-36)
by Los Alamos National Laboratory, which is
operated by the University of California for the
U.S. Department of Energy. The U.S.
Government is licensed to use, reproduce, and
distribute this software. Permission is granted
to the public to copy and use this software
without charge, provided that this Notice and
any statement of authorship are reproduced on
all copies. Neither the Government nor the
University makes any warranty, express or
implied, or assumes any liability or
responsibility for the use of this software.
*/

extern "C" {
void celldiffusionv1res3d_(const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const double&,
                           const double&,
                           const double*,
                           const int&,
                           const double*,
                           const int&,
                           const double*,
                           const int&,
                           const double*,
                           const double*,
                           const double*,
                           const double*,
                           const int&,
                           double*);

void celldiffusionv2res3d_(const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const double&,
                           const double&,
                           const double*,
                           const int&,
                           const double*,
                           const int&,
                           const double*,
                           const double*,
                           const double*,
                           const double*,
                           const int&,
                           double*);

void cellpoissonv1res3d_(const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const double&,
                         const double*,
                         const int&,
                         const double*,
                         const double*,
                         const double*,
                         const double*,
                         const int&,
                         const double*);

void celldiffusionv1apply3d_(const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const double&,
                             const double&,
                             const double*,
                             const int&,
                             const double*,
                             const int&,
                             const double*,
                             const double*,
                             const double*,
                             const double*,
                             const int&,
                             double*);

void celldiffusionv2apply3d_(const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const double&,
                             const double&,
                             const double*,
                             const int&,
                             const double*,
                             const double*,
                             const double*,
                             const double*,
                             const int&,
                             double*);

void cellpoissonv2apply3d_(const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const double&,
                           const double*,
                           const double*,
                           const double*,
                           const double*,
                           const int&,
                           const double*);

void celldiffusionflux3d_(const int&,
                          const int&,
                          const int&,
                          const int&,
                          const int&,
                          const int&,
                          const double*,
                          const double*,
                          const double*,
                          const double*,
                          const int&,
                          const double*,
                          double*,
                          double*,
                          double*);

void cellpoissonflux3d_(const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const double*,
                        const int&,
                        const double*,
                        double*,
                        double*,
                        double*);

void celldiffusionoffdiag3d_(const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const double*,
                             const double&,
                             const double*,
                             const double*,
                             const double*,
                             const int&,
                             const double*);

void cellpoissonoffdiag3d_(const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const double*,
                           const double&,
                           const int&,
                           const double*);

void celldiffusionv1diag3d_(const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const double&,
                            const double*,
                            const int&,
                            const double*);

void celldiffusionv2diag3d_(const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const double&,
                            const int&,
                            const double*);

void cellpoissondiag3d_(const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const double*);

void adjcelldiffusiondiag3d_(const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const double*,
                             const double&,
                             const double*,
                             const double*,
                             const double*,
                             const int&,
                             const double*);

void adjcellpoissondiag3d_(const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const int&,
                           const double*,
                           const double&,
                           const int&,
                           const double*);

void adjcelldiffusioncfdiag3d_(const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const double*,
                               const double&,
                               const double*,
                               const double*,
                               const double*,
                               const int&,
                               const double*);

void adjcellpoissoncfdiag3d_(const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const int&,
                             const double*,
                             const double&,
                             const int&,
                             const double*);

void adjcelldiffusionoffdiag3d_(const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const int&,
                                const double*,
                                const double&,
                                const double&,
                                const double&,
                                const double*,
                                const double*,
                                const double*,
                                const int&,
                                const double*);

void adjcellpoissonoffdiag3d_(const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const double*,
                              const double&,
                              const double&,
                              const double&,
                              const int&,
                              const double*);

void adjcelldiffusioncfoffdiag3d_(const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const double*);

void readjcelldiffusionoffdiag3d_(const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const double*);

void adjcelldiffusioncfbdryrhs3d_(const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const int&,
                                  const double*,
                                  const int&,
                                  const double*,
                                  double*);

void cellsetcorrectionbc3d_(const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const double*,
                            const int&,
                            const double*,
                            const double*,
                            const double*,
                            const int&,
                            const double*,
                            const int*,
                            const int*,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const double&,
                            const double&);

void cellsetpoissoncorrectionbc3d_(const int&,
                                   const int&,
                                   const int&,
                                   const int&,
                                   const int&,
                                   const int&,
                                   const double*,
                                   const int&,
                                   const double*,
                                   const int*,
                                   const int*,
                                   const int&,
                                   const int&,
                                   const int&,
                                   const int&,
                                   const double&,
                                   const double&);

void copycoarsetofine3d_(const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int&,
                         const int*,
                         const double*,
                         const double*);

void copycoarsetofinecorner3d_(const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const int&,
                               const double*,
                               const double*);

    /* level solver prototypes */
void adjcellcrsfinebdryrhs3d_(const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int&,
                              const int*,
                              const double*,
                              const int&,
                              const double*,
                              const double*);

void celladjustsystemrhspatch3d_(const int&,
                                 const int&,
                                 const int&,
                                 const int&,
                                 const int&,
                                 const int*,
                                 const int&,
                                 const double*,
                                 const int&,
                                 const double*,
                                 const int&,
                                 const double*);

void celljacobi3d_(const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int*,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const double*,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const double*,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const double*);

void cellgs3d_(const int&,
               const int&,
               const int&,
               const int&,
               const int&,
               const int&,
               const int&,
               const int*,
               const int&,
               const int&,
               const int&,
               const int&,
               const int&,
               const int&,
               const double*,
               const int&,
               const int&,
               const int&,
               const int&,
               const int&,
               const int&,
               const double*,
               const int&,
               const int&,
               const int&,
               const int&,
               const int&,
               const int&,
               const double*);

void cellrbgs3d_(const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int*,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const double*,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const double*,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 const int&,
                 double*);

void cells7rbgs3d_(const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const double*,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const double*,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   double*);

void cells9rbgs3d_(const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const double*,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const double*,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const int&,
                   const double*);

void cellblock1x1jacobi3d_(const int&,
                           const int&,
                           const int&,
                           const int&,
                           const double*,
                           const int&,
                           const double*,
                           const int&,
                           const double*);

void cellblock2x2jacobi3d_(const int&,
                           const int&,
                           const int&,
                           const int&,
                           const double*,
                           const int&,
                           const double*,
                           const double*,
                           const int&,
                           const double*,
                           const double*);

void ccellblkjacobi3d_(const int&,
                       const int&,
                       const int&,
                       const int&,
                       const int&,
                       const int&,
                       const int&,
                       const int*,
                       const double*,
                       const int&,
                       const int&,
                       const double*,
                       const int&,
                       const double*,
                       const int&,
                       const double*);

void applystencilatpoint3d_(const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int*,
                            const double*,
                            const double&,
                            const double&,
                            const int&,
                            const double*,
                            const int&,
                            const double*,
                            const int&,
                            const double*);

void applystencilonpatch3d_(const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int&,
                            const int*,
                            const double*,
                            const double&,
                            const double&,
                            const int&,
                            const double*,
                            const int&,
                            const double*,
                            const int&,
                            const double*);

void cellblockjacobi3d_(const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int*,
                        const double*,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const double*,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const int&,
                        const double*,
                        const int*,
                        const int&,
                        const int&,
                        const int*,
                        const int&,
                        const int&,
                        const int*,
                        const int&,
                        const int&);
}
